# Generated by Django 4.2.11 on 2024-04-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("side", models.IntegerField(choices=[("BUY", 1), ("SELL", -1)])),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            ("OPEN", 1),
                            ("PARTIALLY_FILLED", 2),
                            ("SUCCESSFULL", 3),
                            ("UNSUCCESSFULL", 4),
                            ("CANCELLED", 5),
                        ],
                        default=1,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
