# Generated by Django 4.2.11 on 2024-04-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="side",
            field=models.IntegerField(choices=[(1, "BUY"), (-1, "SELL")]),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "OPEN"),
                    (2, "PARTIALLY_FILLED"),
                    (3, "SUCCESSFULL"),
                    (4, "UNSUCCESSFULL"),
                    (5, "CANCELLED"),
                ],
                default=1,
            ),
        ),
    ]
